### ISSUE TITLE
Temperature is displayed in Degrees Kelvin 

### ISSUE THREAD

**Issue by ElectricS01** [Flowinity/Flowinity#21]
To replicate go to `/settings/dashboard` and change the `Temperature unit for weather widget` to `Kelvin (Metric Standard)`

The temperature in the top bar will be displayed in `°K` instead of just `K`

<img width="92" alt="image" src="https://github.com/PrivateUploader/PrivateUploader/assets/103579308/c3a8ec3b-c456-4355-ad81-db45f3a6b8b6">

when it should be like

<img width="75" alt="image" src="https://github.com/PrivateUploader/PrivateUploader/assets/103579308/fc5fbdc2-6f42-4b0f-9fda-76c49c53e35e">

**Comment by Troplo** [comment]
This was fixed in api-v4 branch.
