### ISSUE TITLE
Nothing showing up after initial frontend build

### ISSUE THREAD

**Issue by dilllxd** [Flowinity/Flowinity#25]
Hey! Just found this project and wanted to test it out, currently using the docker instructions, on initial start it comes up with the whole frontend being built page and then after I waited a few minutes and checked logs to make sure the frontend was built, going back to https://url/setup brings just a blank page.

Logs from browser console:
![image](https://github.com/PrivateUploader/PrivateUploader/assets/36942187/d658042c-db9c-4246-8638-1346798a7e5c)

Logs from main tpu docker container:
![image](https://github.com/PrivateUploader/PrivateUploader/assets/36942187/52579e16-383c-4cb0-aa51-d3a673e88187)

Logs from redis docker container:
![image](https://github.com/PrivateUploader/PrivateUploader/assets/36942187/da3bc379-23b4-4846-8fbb-480b6eae5457)

Logs from mariadb docker container:
![image](https://github.com/PrivateUploader/PrivateUploader/assets/36942187/eb8df6ad-15db-4d11-adc5-70bef7c9c579)

Let me know if there's anything else you need!

**Comment by Troplo** [comment]
Hey, try the latest Docker image I pushed, previously the Docker image was still on the final v3 release rather than v4 which is the latest now, there were a few issues which were preventing me from updating the image but I've resolved them  so it should work.

Let me know if any issues arise.

**Comment by dilllxd** [comment]
> Hey, try the latest Docker image I pushed, previously the Docker image was still on the final v3 release rather than v4 which is the latest now, there were a few issues which were preventing me from updating the image but I've resolved them so it should work.
> 
> Let me know if any issues arise.

Woo! Works perfectly now, running into the occasional unknown error has occurred but main functionality works perfectly so can't complain. Thanks for fixing it 😄

**Comment by Troplo** [comment]
Glad to hear it worked! Feel free to comment and re-open the issue if you encounter anything else.
